# Group definitions
- name: "Install postgresql"
  ansible.builtin.package:
    name: "postgresql12-server, postgresql12-client"
    state: present
- name: "Install reuirement for db query check"
  package:
    name: "py37-psycopg2"
    state: present
- name: "Check if DB is initialized"
  stat:
    path: /var/db/postgres/data12
  register: dbinit
- name: "Initialize DB"
  command: "/usr/local/etc/rc.d/postgresql initdb"
  when: not dbinit.stat.exists
- name: "Provide postgres config"
  template:
    src: postgresql_freebsd.conf.j2
    dest: /var/db/postgres/data12/postgresql.conf
    mode: 0600
    owner: postgres
    group: postgres
  notify: restart postgres
- name: "Enable postgresql service"
  ansible.builtin.service:
    name: postgresql
    enabled: true
    state: started
- name: "Setup pg_hba"
  postgresql_pg_hba:
    dest: "{{ item['dest']}}"
    contype: "{{ item['contype'] }}"
    users: "{{ item['users'] }}"
    source: "{{ item['source'] }}"
    databases: "{{ item['databases'] }}"
    method: "{{ item['method'] }}"
    state: "{{ item['state'] }}"
  with_items:
    - "{{ postgres_hba }}"
  when: postgres_hba is defined
  notify: restart postgres
- name: "Setup databases"
  ansible.builtin.postgresql_db:
    name: "{{ item['dbname'] }}"
  with_items:
    - "{{ postgres_dbs }}"
  when: postgres_dbs is defined
- name: "Install postgresql roles"
  postgresql_user:
    name: "{{ item.rolename }}"
    db: "{{ item.db }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
  with_items:
    - "{{ postgres_roles }}"
  when: postgres_roles is defined
- name: Install phppgadmin
  ansible.builtin.package:
    name: adminer
    state: present
