---
- name: check if server certificate is there
  stat:
    path: /var/lib/icinga2/certs/{{ inventory_hostname }}.crt
  register: certificatecheck
- name: create master server certificate
  command: icinga2 pki new-cert --cn {{ inventory_hostname }} --key /var/lib/icinga2/certs/{{ inventory_hostname }}.key --csr /var/lib/icinga2/certs/{{ inventory_hostname }}.csr --cert /var/lib/icinga2/certs/{{ inventory_hostname }}.crt && icinga2 pki sign-csr --csr /var/lib/icinga2/certs/{{ inventory_hostname }}.csr --cert /var/lib/icinga2/certs/{{ inventory_hostname }}.crt
  when:
    - certificatecheck.stat.exists == false
    - icinga2signingmaster == inventory_hostname

