---
namespace: imp1sh
name: ansible_managemynetwork
version: 0.2.0
readme: README.md
authors:
  - Jochen Demmer <jochen@libcom.de>
description: A collection of several roles that I need to manage my network. You can use it as well.
license_file: 'LICENSE'
tags: [server, system, management, freebsd, debian, network, services]
dependencies: {}
repository: https://github.com/imp1sh/ansible_managemynetwork
documentation: https://wiki.junicast.de/en/junicast/docs/AnsibleManagemynetworkCollection
homepage: https://github.com/imp1sh/ansible_managemynetwork
issues: https://github.com/imp1sh/ansible_managemynetwork/issues
