---
# tasks file for ansible_podman
- name: Create networks
  containers.podman.podman_network:
    name: "{{ item.name }}"
    driver: "{{ item.driver }}"
    ipv6: "{{ item.ipv6 }}"
  loop: "{{ podman_networks }}"
- name: ensure podman container directories
  ansible.builtin.file:
    path: "{{ item.1 | split(':') | first | ansible.builtin.dirname }}"
    state: directory
  loop: "{{ podman_containers | subelements('volume', 'skip_missing=True') }}"
- name: Create containers
  containers.podman.podman_containers:
    containers: "{{ podman_containers }}"
- name: systemd tasks
  ansible.builtin.include_tasks:
    file: systemd.yml
  loop: "{{ podman_containers }}"
  loop_control:
    loop_var: podman_container
