---
# tasks file for ansible_podman
- name: Create networks
  containers.podman.podman_network:
    name: "{{ item.name }}"
    driver: "{{ item.driver }}"
    ipv6: "{{ item.ipv6 }}"
  loop: "{{ podman_networks }}"
- name: ensure podman container directories
  ansible.builtin.file:
    path: "{{ item.1 | split(':') | first }}"
    state: directory
  loop: "{{ podman_containers | subelements('volume', 'skip_missing=True') }}"
- name: Create containers
  containers.podman.podman_containers:
    containers: "{{ podman_containers }}"
- name: Create Podman Service units
  containers.podman.podman_generate_systemd:
    name: "{{ item.name }}"
    dest: "/etc/systemd/system"
  loop: "{{ podman_containers }}"
- name: Enable systemd units
  ansible.builtin.systemd:
    name: "container-{{ item.name }}"
    daemon_reload: yes
    state: started
    enabled: yes
  loop: "{{ podman_containers }}"
