- name: Install chrony package
  ansible.builtin.package:
    name: "chrony"
    state: present
- name: Implant chrony configuration file
  ansible.builtin.template:
    src: chronyalpine.conf.j2
    dest: /etc/chrony/chrony.conf
- name: Enable chrony service
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true
  ignore_errors: yes
