---
nginxphp_autoindex: 'off'
nginxphp_defaultbindip: "::"
nginxphp_fpmlisten: "{{ nginxphp_fpmsocketpath }}"
nginxphp_fpmlistenmode: "0660"
nginxphp_phptimezone: "Europe/Berlin"
nginxphp_phpversionalpine: "7"
nginxphp_phpversiondebian: "7.4"
nginxphp_phpversionfreebsd: "74"
