---
# tasks file for ansible_netbox2yaml
- name: Run prefix task
  ansible.builtin.include_tasks:
    file: prefixes.yml
  when: nb_fetch_prefixes
- name: Run devices task
  ansible.builtin.include_tasks:
    file: devices.yml
  when: nb_fetch_devices
