---
- name: make sure deploy path exists
  ansible.builtin.file:
    path: "{{ fileitem.dest | ansible.builtin.dirname }}"
    state: directory
  when: fileitem.state == "present"
- name: Deploy current item
  ansible.builtin.copy:
    src: "{{ fileitem.src }}"
    dest: "{{ fileitem.dest }}"
  when: fileitem.state == "present"
- name: Remove current item
  ansible.builtin.file:
    path: "{{ fileitem.dest }}"
  when: fileitem.state == "absent"
