---
- name: Showing current user
  debug:
    var: user.name
- name: Set fact for package install
  ansible.builtin.set_fact:
    packages_installrole: "{{ shellpackages[user.shell] }}"
  when: user.shell is defined
- name: Install package for shell
  ansible.builtin.include_role:
    name: imp1sh.ansible_managemynetwork.ansible_packages
  when: user.shell is defined
- name: set users shell for this OS
  set_fact:
    usershell: "{{ shells[user.shell] }}"
  when: user.shell is defined
- name: check if the host is in the list
  ansible.builtin.include_tasks: "justdoit.yml"
  when:
    - user.createonhosts is defined
    - inventory_hostname in user.createonhosts
- name: check if the group associates with host
  ansible.builtin.include_tasks: "checkgroup.yml"
  when: user.createonhost_bygroup is defined
  loop: "{{ user.createonhost_bygroup }}"
  loop_control:
    loop_var: groupname
- name: Deploy files (optional)
  ansible.builtin.include_tasks: "deployfiles.yml"
  loop: "{{ user.deployfiles }}"
  loop_control:
    loop_var: fileitem
  when: user.deployfiles is defined
