- name: Install mariadb and associated packages
  apk:
          name: mariadb-server-utils, mariadb-client, mariadb, mariadb-common, mariadb-mytop, phpmyadmin
          state: present
- name: Install mariadb server configuration
  template:
          src: mariadb-server.cnf.j2
          dest: /etc/my.cnf.d/mariadb-server.cnf
  notify: restart mariadb
- name: enable mariadb server
  service:
          name: mariadb
          enabled: yes
          state: started
- name: Install packages for phpmyadmin
  apk:
          name: lighttpd, php7-common, php7-iconv, php7-json, php7-gd, php7-curl, php7-xml, php7-mysqli, php7-imap, php7-cgi, fcgi, php7-pdo, php7-pdo_mysql, php7-soap, php7-xmlrpc, php7-posix, php7-mcrypt, php7-gettext, php7-ldap, php7-ctype, php7-dom, php-mysqli
          state: present
- name: Install lighttpd.conf
  copy:
          src: lighttpd.conf
          dest: /etc/lighttpd/lighttpd.conf
  notify: restart lighttpd
- name: Install fastcgi.conf
  template:
          src: mod_fastcgi.conf.j2
          dest: /etc/lighttpd/mod_fastcgi.conf
  notify: restart lighttpd
- name: Enable lighttpd
  service:
          name: lighttpd
          enabled: yes
          state: started
