---
- name: Borgmatic requirements
  ansible.builtin.package:
    name: "{{ borgmatic_package_requirements }}"
    state: present
  when: borgmatic_package_requirements is defined
# package manager
- name: borg backup via package manager
  ansible.builtin.package:
    name: "{{ borgmatic_packagename_borg }}"
    state: "{{ borgmatic_package_state }}"
- name: borgmatic via package manager
  ansible.builtin.package:
    name: "{{ borgmatic_packagename_borgmatic }}"
    state: "{{ borgmatic_package_state }}"
# pip  
- name: Install pip for pip installation
  ansible.builtin.package:
    name: "{{ borgmatic_pip_package }}"
    state: present
  when: borgmatic_via_pip
- name: Install borgmatic via pip
  ansible.builtin.pip:
    name: borgmatic
  when: borgmatic_via_pip
- name: Install borg via pip
  ansible.builtin.pip:
    name: borgbackup
  when: borgmatic_via_pip
# Apprise
- name: Install apprise if needed
  ansible.builtin.include_role:
    name: imp1sh.ansible_managemynetwork.ansible_apprise
  when: borgmatic_apprise
# config dir
- name: Make sure borgmatic config dir exists
  file:
    path: "{{ borgmatic_pathconfig }}"
    state: directory
    owner: "{{ borgmatic_pathconfig_owner }}"
    group: "{{ borgmatic_pathconfig_group }}"
    mode: 0700
