---
- name: make sure root user has ssh public key
  user:
    name: "root"
    generate_ssh_key: yes
  register: rootuser
- name: provide root user's public key to destination machine
  authorized_key:
    user: "{{ borgmatic_sshkey_user }}"
    state: present
    key: "{{ rootuser['ssh_public_key'] }}"
  delegate_to: "{{ borgmatic_sshkey_targethost }}"
- name: install target hosts fingerprint to known hosts
  known_hosts:
    path: "{{ borgmatic_file_sshknownhosts }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -trsa ' + borgmatic_sshkey_targethost) }}"
    name: "{{ borgmatic_sshkey_targethost }}"
    state: present
