---
- name: Install apprise
  ansible.builtin.package:
    name: "{{ packagepip }}"
    state: present
- name: install apprise via pip
  ansible.builtin.pip:
    name: "{{ packageapprisepip }}"
  when:
    - apprise_via_pip
- name: Install apprise via package manager
  ansible.builtin.package:
    name: "{{ package_name }}"
  when:
    - not apprise_via_pip
- name: Get apprise path
  ansible.builtin.command: which apprise
  register: apprisequery
- name: install borgmatic template (optional)
  ansible.builtin.template:
    src: apprise_borgmatic.sh.jinja2
    dest: "{{ path_apprise_script }}/apprise_borgmatic.sh"
    mode: 0750
    owner: root
  when: borgmatic_apprise
