---
# create password with mkpasswd -m sha-512 for example, depends on what hash you want
- name: make sure sudo group exists
  ansible.builtin.group:
    name: "sudo"
    state: present
- name: create users that come from group definitions
  ansible.builtin.user:
    name: "{{ item.username }}"
    comment: "{{ item.comment |default(omit) }}"
    password: "{{ item.pw | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    home: "{{ item.home | default(omit) }}"
    append: yes
    groups: "{{ item.groups | default(omit) }}"
  loop:
    "{{ createusers_group }}"
  when: createusers_group is defined
- name: create users that come from host definitions
  ansible.builtin.user:
    name: "{{ item.username }}"
    comment: "{{ item.comment |default(omit) }}"
    password: "{{ item.pw | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    home: "{{ item.home | default(omit) }}"
    append: yes
    groups: "{{ item.groups | default(omit) }}"
  loop:
    "{{ createusers_host }}"
  when: createusers_host is defined
