- name: Install curl from apk
  apk:
          name: curl
          state: present
- name: Install dehydrated bin manually from git
  copy:
          src: dehydrated/dehydrated
          dest: /usr/local/bin/dehydrated
          owner: root
          group: root
          mode: 0755
- name: Setup dehydrated etc directory
  file:
          path: /etc/dehydrated
          state: directory
          mode: 0755
          owner: "{{ DEHYDRATED_USER }}"
          group: "{{ DEHYDRATED_GROUP }}"
- name: Setup dehydrated basedir directory
  file:
          path: "{{ BASEDIR }}"
          state: directory
          mode: 0755
          owner: "{{ DEHYDRATED_USER }}"
          group: "{{ DEHYDRATED_GROUP }}"
- name: copy dehydrated config
  template:
          src: dehydratedconfig
          dest: /etc/dehydrated/config
          owner: "{{ DEHYDRATED_USER }}"
          group: "{{ DEHYDRATED_GROUP }}"
          mode: 0750
- name: copy pdnsapi hook script
  copy:
          src: pdns_api.sh/pdns_api.sh
          dest: "{{ BASEDIR }}/pdns_api.sh"
          owner: "{{ DEHYDRATED_USER }}"
          group: "{{ DEHYDRATED_USER }}"
          mode: 0755
- name: setup dehydrated domains.txt
  template:
          src: domains.txt
          dest: "{{ BASEDIR }}/domains.txt"
          owner: "{{ DEHYDRATED_USER }}"
          group: "{{ DEHYDRATED_GROUP }}"
  when: dehydrateddomains is defined
  notify:
          - dehydrated cron
- name: run dehydrated to accept terms
  command: /usr/local/bin/dehydrated --register --accept-terms
- name: setup dehydrated cronjob
  cron:
          name: renew certificates dehydrated
          minute: "0"
          hour: "12"
          job: "/usr/local/bin/dehydrated -c"
