- name: Install curl from apk
  package:
    name: curl
    state: present
- name: Install dehydrated bin manually from git
  copy:
    src: dehydrated/dehydrated
    dest: "{{ dehydrated_binpath }}"
    owner: root
    group: root
    mode: 0755
- name: Setup dehydrated etc directory
  file:
    path: "{{ dehydrated_basedir }}"
    state: directory
    mode: 0755
    owner: "{{ dehydrated_user }}"
    group: "{{ dehydrated_group }}"
- name: Setup dehydrated basedir directory
  file:
    path: "{{ dehydrated_basedir }}"
    state: directory
    mode: 0755
    owner: "{{ dehydrated_user }}"
    group: "{{ dehydrated_group }}"
- name: copy dehydrated config
  template:
    src: dehydratedconfig
    dest: "{{ dehydrated_basedir }}/config"
    owner: "{{ dehydrated_user }}"
    group: "{{ dehydrated_group }}"
    mode: 0750
- name: fetch pdns_api.sh from url
  get_url:
    url: https://raw.githubusercontent.com/silkeh/pdns_api.sh/master/pdns_api.sh
    dest: "{{ dehydrated_basedir }}/pdns_api.sh"
    mode: 0755
    owner: "{{ dehydrated_user }}"
    group: "{{ dehydrated_user }}"
- name: setup dehydrated domains.txt
  template:
    src: domains.txt
    dest: "{{ dehydrated_basedir }}/domains.txt"
    owner: "{{ dehydrated_user }}"
    group: "{{ dehydrated_group }}"
  when: dehydrateddomains is defined
  notify:
    - dehydrated cron
- name: run dehydrated to accept terms
  command: "{{ dehydrated_binpath }} --register --accept-terms"
- name: setup dehydrated cronjob
  cron:
    name: renew certificates dehydrated
    minute: "0"
    hour: "12"
    job: "{{ dehydrated_binpath }} -c"
