---
- name: include OS vars
  include_vars: "{{ ansible_os_family }}.yml"
# Installations
- name: Install needed packages
  package:
    name: "{{ dehydrated_packages }}"
    state: present
- name: Alpine install dehydrated manually from git
  get_url:
    url: https://raw.githubusercontent.com/dehydrated-io/dehydrated/master/dehydrated
    dest: "{{ dehydrated_binpath }}"
    owner: root
    group: root
    mode: 0755
  when: ansible_distribution == "Alpine"
# Setup Directories and files
- name: Setup dehydrated basedir directory
  file:
    path: "{{ dehydrated_basedir }}"
    state: directory
    mode: 0755
    owner: "{{ dehydrated_user }}"
    group: "{{ dehydrated_group }}"
- name: copy dehydrated config
  template:
    src: dehydratedconfig
    dest: "{{ dehydrated_confdir }}/config"
    owner: "{{ dehydrated_user }}"
    group: "{{ dehydrated_group }}"
    mode: 0750
  notify: dehydrated cron
- name: setup dehydrated wellknown path
  file:
    path: "{{ dehydrated_wellknown }}"
    state: directory
    mode: 0750
    owner: "{{ dehydrated_user }}"
    group: "{{ dehydrated_group }}"
  when: dehydrated_wellknown is defined
- name: ensure accounts directory
  file:
    path: "{{ dehydrated_basedir }}/accounts"
    state: directory
    mode: 0750
    owner: "{{ dehydrated_user }}"
    group: "{{ dehydrated_group }}"
- name: ensure chains directory
  file:
    path: "{{ dehydrated_basedir }}/chains"
    state: directory
    mode: 0750
    owner: "{{ dehydrated_user }}"
    group: "{{ dehydrated_group }}"
- name: ensure acme-challenges directory
  file:
    path: "{{ dehydrated_basedir }}/acme-challenges"
    state: directory
    mode: 0750
    owner: "{{ dehydrated_user }}"
    group: "{{ dehydrated_group }}"
- name: fetch pdns_api.sh hook script from url
  get_url:
    url: https://raw.githubusercontent.com/silkeh/pdns_api.sh/master/pdns_api.sh
    dest: "{{ dehydrated_basedir }}/pdns_api.sh"
    mode: 0755
    owner: "{{ dehydrated_user }}"
    group: "{{ dehydrated_group }}"
- name: setup dehydrated domains.txt
  template:
    src: domains.txt
    dest: "{{ dehydrated_confdir }}/domains.txt"
    owner: "{{ dehydrated_user }}"
    group: "{{ dehydrated_group }}"
  when: dehydrated_domains is defined
  notify:
    - dehydrated cron
# Accept terms and cron
- name: run dehydrated to accept terms
  command: "{{ dehydrated_binpath }} --register --accept-terms"
- name: setup dehydrated cronjob
  cron:
    name: renew certificates dehydrated
    minute: "0"
    hour: "12"
    job: "{{ dehydrated_binpath }} -c -g"
